
// Code generated by go-boilerplate. DO NOT EDIT.
package container

import (
	"go.uber.org/dig"

	"github.com/adityarifqyfauzan/go-boilerplate/internal/module/authentication")

func moduleContainer(container *dig.Container) {

	authentication.InitContainer(container)
}