
// Code generated by go-boilerplate. DO NOT EDIT.
package container

import (
	"go.uber.org/dig"

	"github.com/adityarifqyfauzan/go-boilerplate/internal/module/auth"
	"github.com/adityarifqyfauzan/go-boilerplate/internal/module/user")

func moduleContainer(container *dig.Container) {

	auth.InitContainer(container)
	user.InitContainer(container)
}