
// Code generated by go-boilerplate. DO NOT EDIT.
package container

import (
	"github.com/adityarifqyfauzan/go-boilerplate/internal/model"
	"github.com/adityarifqyfauzan/go-boilerplate/internal/repository"
	"go.uber.org/dig"
)

func repositoryContainer(container *dig.Container) {

	if err := container.Provide(repository.NewRepository[model.Role]); err != nil {
		panic(err)
	}

	if err := container.Provide(repository.NewRepository[model.User]); err != nil {
		panic(err)
	}

	if err := container.Provide(repository.NewRepository[model.UserRole]); err != nil {
		panic(err)
	}

	if err := container.Provide(repository.NewRepository[model.UserStatus]); err != nil {
		panic(err)
	}
}
