development:
  dialect: mysql
  datasource: root:rootpass@tcp(127.0.0.1:3306)/go_starter_kit?parseTime=true
  dir: internal/database/migrations
  table: migrations

prod:
  dialect: mysql
  datasource: root:pass@tcp(ipaddress:3306)/go_starter_kit?parseTime=true
  dir: internal/database/migrations
  table: migrations